[32m2022-11-04 12:00:47 -0700[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - dbfb95fe-23c5-4e84-8849-540744f84594 - 1745176 - vis_raw_fetch_todb - LOGS_CAPTURED - Started capturing logs for step: vis_raw_fetch_todb.
[32m2022-11-04 12:00:47 -0700[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - dbfb95fe-23c5-4e84-8849-540744f84594 - 1745176 - vis_raw_fetch_todb - STEP_START - Started execution of step "vis_raw_fetch_todb".
[32m2022-11-04 12:00:47 -0700[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - dbfb95fe-23c5-4e84-8849-540744f84594 - 1745176 - vis_raw_fetch_todb - STEP_FAILURE - Execution of step "vis_raw_fetch_todb" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "vis_raw_fetch_todb"::

AttributeError: 'list' object has no attribute 'yamcslient'

Stack Trace:
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/site-packages/dagster/_core/execution/plan/utils.py", line 47, in solid_execution_error_boundary
    yield
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/site-packages/dagster/_utils/__init__.py", line 430, in iterate_with_context
    next_output = next(iterator)
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/site-packages/dagster/_core/execution/plan/compute_generator.py", line 74, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/Work/VIPER/dagster/visdag/visdag/assets/vis_raw_fetch.py", line 51, in vis_raw_fetch_todb
    print(args.yamcslient)
[0m
