[32m2022-10-25 14:48:13 -0700[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - db8ef3f3-ea3c-4283-bb0f-d8fc06201c4d - 2087667 - vis_raw_fetch2 - LOGS_CAPTURED - Started capturing logs for step: vis_raw_fetch2.
[32m2022-10-25 14:48:14 -0700[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - db8ef3f3-ea3c-4283-bb0f-d8fc06201c4d - 2087667 - vis_raw_fetch2 - STEP_START - Started execution of step "vis_raw_fetch2".
usage: __main__.py [-h] [-v] [--version] [-y YAMCSCLIENT] [-d DBURL] [-j JSON]
                   [-o OUTDIR]
__main__.py: error: argument -v/--verbose: ignored explicit argument 'erbose'
[32m2022-10-25 14:48:14 -0700[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - db8ef3f3-ea3c-4283-bb0f-d8fc06201c4d - 2087667 - vis_raw_fetch2 - STEP_FAILURE - Execution of step "vis_raw_fetch2" failed.

SystemExit: 2

Stack Trace:
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_plan.py", line 225, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_step.py", line 361, in core_dagster_event_sequence_for_step
    _step_output_error_checked_user_event_sequence(step_context, user_event_sequence)
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_step.py", line 69, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/site-packages/dagster/_core/execution/plan/compute.py", line 174, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn):
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/site-packages/dagster/_core/execution/plan/compute.py", line 151, in _yield_compute_results
    user_event_generator,
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/site-packages/dagster/_utils/__init__.py", line 430, in iterate_with_context
    next_output = next(iterator)
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/site-packages/dagster/_core/execution/plan/compute_generator.py", line 74, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/Work/VIPER/dagster/visdag/visdag/assets/watcher.py", line 36, in vis_raw_fetch2
    watcher.main(args)
  File "/Work/VIPER/dagster/visdag/visdag/watcher.py", line 139, in main
    args = parser.parse_args(args)
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/argparse.py", line 1794, in parse_known_args
    self.error(str(err))
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/argparse.py", line 2508, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/Work/Anaconda/anaconda3_2022_Oct/envs/dagster/lib/python3.7/argparse.py", line 2495, in exit
    _sys.exit(status)
[0m
